// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_app/rust/api/model.dart';
import 'package:localsend_app/rust/api/stream.dart';
import 'package:localsend_app/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `flatten_file_result`, `register_dto_from_v2`, `respond`, `respond`, `send_content`, `spawn_internal_event_forwarder`, `spawn_v2_event_forwarder`, `spawn_web_send_event_forwarder`, `take_target`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `drop`, `eq`, `eq`, `fmt`, `fmt`

RsHttpServer createHttpServer() => RustLib.instance.api.crateApiHttpServerCreateHttpServer();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsHttpServer>>
abstract class RsHttpServer implements RustOpaqueInterface {
  Stream<RsHttpServerEvent> listen();

  Future<void> start({
    required int port,
    RsHttpServerTlsConfig? tls,
    required RsHttpServerInfo info,
    RsHttpServerInternalConfig? internal,
    RsHttpServerV2Config? v2,
    RsHttpServerWebSendConfig? webSend,
  });

  void stop();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsHttpServerEvent>>
abstract class RsHttpServerEvent implements RustOpaqueInterface {
  List<String>? args();

  FileDto? file();

  String? fileId();

  Map<String, FileDto>? files();

  RegisterDto? info();

  String? ip();

  RsHttpServerEventKind kind();

  RsHttpServerSessionEndReason? reason();

  String? sessionId();

  RsHttpServerFileDownloadRequest? takeFileDownloadRequest();

  RsHttpServerFileUploadRequest? takeFileUploadRequest();

  RsHttpServerPrepareDownloadRequest? takePrepareDownloadRequest();

  RsHttpServerPrepareUploadRequest? takePrepareUploadRequest();

  String? userAgent();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsHttpServerFileDownloadRequest>>
abstract class RsHttpServerFileDownloadRequest implements RustOpaqueInterface {
  Future<void> provideBytes({required List<int> data});

  Future<void> provideFileDescriptor({required int fd});

  Future<void> providePath({required String path});

  Future<void> provideStream({required Dart2RustStreamReceiver stream});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsHttpServerFileUploadRequest>>
abstract class RsHttpServerFileUploadRequest implements RustOpaqueInterface {
  Stream<Uint8List> receive();

  Future<void> saveToFileDescriptor({required int fd});

  Future<void> saveToPath({required String path});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsHttpServerPrepareDownloadRequest>>
abstract class RsHttpServerPrepareDownloadRequest implements RustOpaqueInterface {
  Future<void> accept();

  Future<void> decline();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsHttpServerPrepareUploadRequest>>
abstract class RsHttpServerPrepareUploadRequest implements RustOpaqueInterface {
  Future<void> accept({required Set<String> fileIds});

  Future<void> decline();
}

enum RsHttpServerEventKind {
  show_,
  register,
  prepareUpload,
  fileUpload,
  sessionEnd,
  prepareDownload,
  fileDownload,
}

class RsHttpServerInfo {
  final String alias;
  final String version;
  final String? deviceModel;
  final DeviceType? deviceType;
  final String token;

  const RsHttpServerInfo({
    required this.alias,
    required this.version,
    this.deviceModel,
    this.deviceType,
    required this.token,
  });

  @override
  int get hashCode => alias.hashCode ^ version.hashCode ^ deviceModel.hashCode ^ deviceType.hashCode ^ token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsHttpServerInfo &&
          runtimeType == other.runtimeType &&
          alias == other.alias &&
          version == other.version &&
          deviceModel == other.deviceModel &&
          deviceType == other.deviceType &&
          token == other.token;
}

class RsHttpServerInternalConfig {
  final String showToken;

  const RsHttpServerInternalConfig({
    required this.showToken,
  });

  @override
  int get hashCode => showToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is RsHttpServerInternalConfig && runtimeType == other.runtimeType && showToken == other.showToken;
}

enum RsHttpServerSessionEndReason {
  finished,
  cancelled,
}

class RsHttpServerTlsConfig {
  final String cert;
  final String privateKey;

  const RsHttpServerTlsConfig({
    required this.cert,
    required this.privateKey,
  });

  @override
  int get hashCode => cert.hashCode ^ privateKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsHttpServerTlsConfig && runtimeType == other.runtimeType && cert == other.cert && privateKey == other.privateKey;
}

class RsHttpServerV2Config {
  final String? pin;

  const RsHttpServerV2Config({
    this.pin,
  });

  @override
  int get hashCode => pin.hashCode;

  @override
  bool operator ==(Object other) => identical(this, other) || other is RsHttpServerV2Config && runtimeType == other.runtimeType && pin == other.pin;
}

class RsHttpServerWebSendConfig {
  final Map<String, FileDto> files;
  final String? pin;
  final RsHttpServerWebSendI18n i18N;

  const RsHttpServerWebSendConfig({
    required this.files,
    this.pin,
    required this.i18N,
  });

  @override
  int get hashCode => files.hashCode ^ pin.hashCode ^ i18N.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsHttpServerWebSendConfig && runtimeType == other.runtimeType && files == other.files && pin == other.pin && i18N == other.i18N;
}

class RsHttpServerWebSendI18n {
  final String waiting;
  final String enterPin;
  final String invalidPin;
  final String tooManyAttempts;
  final String rejected;
  final String files;
  final String fileName;
  final String size;

  const RsHttpServerWebSendI18n({
    required this.waiting,
    required this.enterPin,
    required this.invalidPin,
    required this.tooManyAttempts,
    required this.rejected,
    required this.files,
    required this.fileName,
    required this.size,
  });

  @override
  int get hashCode =>
      waiting.hashCode ^
      enterPin.hashCode ^
      invalidPin.hashCode ^
      tooManyAttempts.hashCode ^
      rejected.hashCode ^
      files.hashCode ^
      fileName.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsHttpServerWebSendI18n &&
          runtimeType == other.runtimeType &&
          waiting == other.waiting &&
          enterPin == other.enterPin &&
          invalidPin == other.invalidPin &&
          tooManyAttempts == other.tooManyAttempts &&
          rejected == other.rejected &&
          files == other.files &&
          fileName == other.fileName &&
          size == other.size;
}
